n=int(input('Nhập tháng trong nămnăm: '))
if n==1: print(n,". January")
elif n==2: print(n,". February")
elif n==3: print(n,". March")
elif n==4: print(n,". April")
elif n==5: print(n,". May")
elif n==6: print(n,". June")
elif n==7: print(n,". July")
elif n==8: print(n,". August")
elif n==9: print(n,". September")
elif n==10: print(n,". October")
elif n==11: print(n,". November")
elif n==12: print(n,". December")
else:
    print("Không hợp lệ. Vui lòng nhập lại")