n = int(input("Nhập số nguyên dương n: "))
while n <= 0:
    n = int(input("Nhập lại số nguyên dương n: "))
S4, i = 0, 1
while i <= n:
    S4 += i**2
    i += 1
print("S4 =", S4)
S5, i = 0, 1
while i <= n:
    S5 += (2*i + 1)**3
    i += 1
print("S5 =", S5)
S6, i = 0, 1
while i <= n:
    S6 += (2*i)**4
    i += 1
print("S6 =", S6)
