ma_sv = int(input("nhập mã sinh viên: "))
ho_ten = input("nhập họ và tên: ")
que_quan = input("nhập quê quán: ")
nam_sinh = int(input("nhập năm sinh: "))
diem_tb = float(input("nhập điểm trung bình: "))
print("===Thông tin sinh viên===")
print("Mã sinh viên:    ",ma_sv)
print("Họ và tên:       ",ho_ten)
print("Quê quán:        ",que_quan)
print("Năm sinh:        ",nam_sinh)
print("Điểm trung bình: ",diem_tb)
