ma = int(input("Nhập mã số sinh viên: "))
ten = str(input("Nhập họ tên: "))
que = str(input("Nhập quê quán: "))
sinh = int(input("Nhập năm sinh: "))
dtb = float(input("Nhập điểm trung bình các năm học: "))
print(f"Mã số sinh viên: {ma}")
print(f"Họ tên: {ten}")
print(f"Quê quán: {que} ")
print(f"Năm sinh: {sinh}")
print(f"Điểm trung bình các năm: {dtb}")