#Bai 1:
ma_so_sinh_vien = int(input("Nhập mã số sinh viên: "))
ho_ten = input("Nhập họ tên: ")
que_quan = input("Nhập quê quán: ")
nam_sinh = int(input("Nhập năm sinh: "))  
diem_trung_binh = float(input("Nhập điểm trung bình các năm học: ")) 
print("\nThông tin sinh viên vừa nhập:")
print("Mã số sinh viên:", ma_so_sinh_vien)
print("Họ tên:", ho_ten)
print("Quê quán:", que_quan)
print("Năm sinh:", nam_sinh)
print("Điểm trung bình các năm học:", diem_trung_binh)