import random
n=int(input('nhap so sinh vien tham gia'))
A=set(random.choices(range(2,n),k=7))
B=set(random.choices(range(2,n),k=6))
C=set(random.choices(range(2,n),k=5))
print('tap hop a la sinh vien thi C++',A)
print('tap hop B la sinh vien thi Java',B)
print('tap hop C la sinh vien thi python',C)
print('tap hop sinh vien thi 3 ngon ngu',A&B&C)
print('tap hop sinh vien thi 2 ngon ngu',(A&B).union(A&C).union(B&C))
print('tap hop sinh vien thi 1 ngon ngu',A.difference(B).difference(C))
